AUTHENTICATION = '?auth?'
REFRESH = '?refresh?'
REFRESH_UPDATE = '?refreshupdate?'
DISCONNECT = '?bye?'
INTRODUCE = '?mynameis?'
PEERSEND = '?peersend?'
FILETRANSFER = '?trans?'
FILETRANSBEGIN = '?fbegin?'
FILETRANSEND = '?fend'
ADVERTISEFILE = '?advertisefile?'
FILENAME = '?fname?'

